#!/usr/bin/env python
# coding: utf-8

# ANS1

# In[1]:


"""When it comes to choosing a database the biggest decisions is picking a relational (SQL)
or non-relational (NoSQL) data structure. While both the databases are viable options still there are 
certain key differences between the two that users must 
keep in mind when making a decision.

SQL                                                                  	NoSQL
RELATIONAL DATABASE MANAGEMENT SYSTEM (RDBMS)	
                                                                      Non-relational or distributed database system.
These databases have fixed or static or predefined schema     	      They have dynamic schema
These databases are not suited for hierarchical data storage.	      These databases are best suited for hierarchical data storage.
These databases are best suited for complex queries	These databases
are not so good for complex queries
Vertically Scalable	Horizontally scalable
Follows ACID property	                                               Follows CAP(consistency, availability, partition tolerance)
Examples: MySQL, PostgreSQL, Oracle, MS-SQL Server, etc                	Examples: MongoDB, GraphQL, HBase, Neo4j, Cassandra, etc"""


# ANS2

# In[2]:


"""Data Definition Language(DDL) is a subset of SQL and a part of DBMS(Database Management System).
DDL Commands :
In this section, We will cover the following DDL commands as follows.

1.Create
2.Alter 
3.truncate
4.drop


CREATE :
This command is used to create a new table in SQL. The user has to give information like table name, 
column names, and their datatypes.

CREATE TABLE Student_info
(
College_Id number(2),
College_name varchar(30),
Branch varchar(10)
);

ALTER :
This command is used to add, delete or change columns in the existing table. 
The user needs to know the existing table name and can do add, 
delete or modify tasks easily.

ALTER TABLE Student_info
ADD CGPA number;


TRUNCATE :
This command is used to remove all rows from the table, but the structure of the table still exists.

TRUNCATE TABLE Student_info;

DROP :
This command is used to remove an existing table along with its structure from the Database.

DROP TABLE Student_info;

"""


# ANS3

# In[3]:


"""DML(Data Manipulation Language): 
The SQL commands that deals with the manipulation of data present in the database belong to DML or
Data Manipulation Language and this includes
most of the SQL statements.

INSERT : It is used to insert data into a table.
UPDATE: It is used to update existing data within a table.
DELETE : It is used to delete records from a database table.

INSERT INTO table_name (column1, column2, column3) VALUES ( value1, value2, value3);


UPDATE table_name SET column1 = value1, column2 = value2, 
WHERE condition;

DELETE FROM table_name WHERE some_condition;
"""


# ANS4

# In[4]:


"""DQL (Data Query Language):
DQL statements are used for performing queries on the data within schema objects. 
The purpose of the DQL Command is to get some
schema relation based on the query passed to it.

Example:

SELECT column1,column2 FROM table_name 
"""


# ANS5

# In[5]:


"""1.PRIMARYKEY:-A primary key is used to ensure that data in the specific column is unique. A column cannot have NULL values. It is either an existing table column or a column that is specifically generated by the database according to a defined sequence. 

Example: Refer the figure – 
STUD_NO, as well as STUD_PHONE both

2.FOREIGNKEY:-A foreign key is a column or group of columns in a relational database table that provides a link between data in two tables. It is a column (or columns) that references a column (most often the primary key) of another table. 

Example: Refer the figure: – 
STUD_NO in STUDENT_COURSE is a foreign key to STUD_NO in STUDENT relation
"""


# ANS6

# In[6]:


"""import mysql.connector
mydb = mysql.connector.connect(
  host="localhost",
  user="abc",
  password="password"
)
print(mydb)
mycursor = mydb.cursor()
mycursor.execute("SHOW DATABASES")
for x in mycursor:
  print(x)


A cursor is an object which helps to execute the query and fetch the records from the database. 
The cursor plays a very important role in executing the query. 
This article will learn some deep information about the execute methods and how to use those methods in python.

Method cursor.execute ():
The execute () method helps us to execute the query and return records according to the query. The syntax of the execute () function is:

execute (query, args = None)
  
"""


# In[7]:


"""Order	Clause	Function
1	FROM	Tables are joined to get the base data.
2	WHERE	The base data is filtered.
3	GROUP BY	The filtered base data is grouped.
4	HAVING	The grouped base data is filtered.
5	SELECT	The final data is returned.
6	ORDER BY	The final data is sorted.
7	LIMIT	The returned data is limited to row count.
"""


# In[ ]:




