# -*- coding: utf-8 -*-
"""ploty assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l8ODLfBFm2-mMFzTrsgUvYmPurfOYJIv
"""

##ANS1
import plotly.graph_objects as go
import seaborn as sns
titanic  = sns.load_dataset('titanic')
fig = go.Figure()
fig.add_trace(go.Scatter(x = titanic.age,y = titanic.fare,mode = 'markers'))

##ANS2

import plotly.express as px
tips = px.data.tips()
fig = px.box(tips, x='day', y='total_bill', color='sex', title='Tips Dataset')
fig.show()

##ANS3

import plotly.express as px
tips = px.data.tips()
fig = px.histogram(tips, x='sex', y='total_bill', color='day', marginal='box', pattern_shape='smoker')
fig.show()

##ANS4

import plotly.graph_objects as go
import seaborn as sns
iris = sns.load_dataset('iris')
fig = go.Figure()
fig.add_trace(go.Scatter(x=iris.sepal_length,y=iris.sepal_width))

##ANS5

import plotly.express as px
import pandas as pd
data = pd.DataFrame({'values': [1, 2, 3, 3, 3, 4, 4, 5, 5, 5, 5]})
fig = px.histogram(data, x='values', nbins=5)
fig.show()

